"""empty message

Revision ID: 3f792c18f08a
Revises: 
Create Date: 2018-01-13 22:50:14.401478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f792c18f08a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('guid', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('post_guid', postgresql.UUID(), nullable=False),
    sa.Column('user_guid', postgresql.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('reply_to_guid', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_comment_guid'), 'comment', ['guid'], unique=True)
    op.create_index(op.f('ix_comment_post_guid'), 'comment', ['post_guid'], unique=False)
    op.create_index(op.f('ix_comment_reply_to_guid'), 'comment', ['reply_to_guid'], unique=False)
    op.create_index(op.f('ix_comment_user_guid'), 'comment', ['user_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_user_guid'), table_name='comment')
    op.drop_index(op.f('ix_comment_reply_to_guid'), table_name='comment')
    op.drop_index(op.f('ix_comment_post_guid'), table_name='comment')
    op.drop_index(op.f('ix_comment_guid'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
